### ISSUE TITLE
请教一下S参数是哪一个参数？

### ISSUE THREAD

**Issue by VergilWu** [happy888888/WeiboTask#6]
感谢作者开源本工具。请问一下文档所说的S参数是哪一个呢？抓包请求很多一个个找来没找到一个key为S的参数，希望作者给予更新补充解释。

**Comment by happy888888** [comment]
微博app的数据包(域名是api.weibo.cn)几乎都带有一个key为S的参数，C参数为app对应的系统，已知"android"，如果用其他系统的app抓包，C参数也需要修改

**Comment by VergilWu** [comment]
感谢作者耐心解答，找到了s参数，一个8位数的字符串。但填写完运行脚本提示 "微博app参数验证失败(请重新填写S参数和C参数):客户端身份校验失败" ，不知道是哪里出了问题。

**Comment by rxrw** [comment]
> 感谢作者耐心解答，找到了s参数，一个8位数的字符串。但填写完运行脚本提示 "微博app参数验证失败(请重新填写S参数和C参数):客户端身份校验失败" ，不知道是哪里出了问题。

我看了下，其中有一个from字段也是要写进去的，作者在代码里写死了，修改一下就好了

**Comment by pfvlz** [comment]
> > 感谢作者耐心解答，找到了s参数，一个8位数的字符串。但填写完运行脚本提示 "微博app参数验证失败(请重新填写S参数和C参数):客户端身份校验失败" ，不知道是哪里出了问题。
> 
> 我看了下，其中有一个from字段也是要写进去的，作者在代码里写死了，修改一下就好了

微博app参数验证失败(请重新填写S参数和C参数):客户端身份校验失败
2021/04/24 17:28:17 没有正确的S参数和C参数,跳过执行微博app任务
2021/04/24 17:28:17 每日积分获取失败：该任务今日已领取过

config.json里面 f参数加到后面。运行还是S C参数验证失败。请问在哪里修改？

**Comment by rxrw** [comment]
之前的pr 作者已经合了，默认配置应该就有f参数

发自我的iPhone

**Comment by pfvlz** [comment]
> 之前的pr 作者已经合了，默认配置应该就有f参数 发自我的iPhone
> […](#)
> 在 2021年4月24日，21:13，pfvlz ***@***.***> 写道： ﻿ 感谢作者耐心解答，找到了s参数，一个8位数的字符串。但填写完运行脚本提示 "微博app参数验证失败(请重新填写S参数和C参数):客户端身份校验失败" ，不知道是哪里出了问题。 我看了下，其中有一个from字段也是要写进去的，作者在代码里写死了，修改一下就好了 config.json里面 f参数加到后面。运行还是S C参数验证失败。请问在哪里修改？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.


设置了F参数。还是出现这个问题。

**Comment by rxrw** [comment]
> > 之前的pr 作者已经合了，默认配置应该就有f参数 发自我的iPhone
> > […](#)
> > 在 2021年4月24日，21:13，pfvlz _**@**_.***> 写道： ﻿ 感谢作者耐心解答，找到了s参数，一个8位数的字符串。但填写完运行脚本提示 "微博app参数验证失败(请重新填写S参数和C参数):客户端身份校验失败" ，不知道是哪里出了问题。 我看了下，其中有一个from字段也是要写进去的，作者在代码里写死了，修改一下就好了 config.json里面 f参数加到后面。运行还是S C参数验证失败。请问在哪里修改？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 设置了F参数。还是出现这个问题。

C==android
F是类似`10B4095012`格式的东西

**Comment by pfvlz** [comment]
是的。 已经找到了from值，是你说的这个。

**Comment by pfvlz** [comment]
> > > 之前的pr 作者已经合了，默认配置应该就有f参数 发自我的iPhone
> > > […](#)
> > > 在 2021年4月24日，21:13，pfvlz _**@**_.***> 写道： ﻿ 感谢作者耐心解答，找到了s参数，一个8位数的字符串。但填写完运行脚本提示 "微博app参数验证失败(请重新填写S参数和C参数):客户端身份校验失败" ，不知道是哪里出了问题。 我看了下，其中有一个from字段也是要写进去的，作者在代码里写死了，修改一下就好了 config.json里面 f参数加到后面。运行还是S C参数验证失败。请问在哪里修改？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > 设置了F参数。还是出现这个问题。
> 
> C==android
> F是类似`10B4095012`格式的东西

是的，已经找到了from值，是你说的这个。运行还是这个问题

**Comment by pfvlz** [comment]
![image](https://user-images.githubusercontent.com/73408957/115983145-193bd980-a5d2-11eb-9610-63d5d0deb64a.png)
任务还是全部没有完成

**Comment by rxrw** [comment]
> > > > 之前的pr 作者已经合了，默认配置应该就有f参数 发自我的iPhone
> > > > […](#)
> > > > 在 2021年4月24日，21:13，pfvlz _**@**_.***> 写道： ﻿ 感谢作者耐心解答，找到了s参数，一个8位数的字符串。但填写完运行脚本提示 "微博app参数验证失败(请重新填写S参数和C参数):客户端身份校验失败" ，不知道是哪里出了问题。 我看了下，其中有一个from字段也是要写进去的，作者在代码里写死了，修改一下就好了 config.json里面 f参数加到后面。运行还是S C参数验证失败。请问在哪里修改？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> > > 
> > > 
> > > 设置了F参数。还是出现这个问题。
> > 
> > 
> > C==android
> > F是类似`10B4095012`格式的东西
> 
> 是的，已经找到了from值，是你说的这个。运行还是这个问题

https://github.com/rxrw/signup-weibo
完全是作者的代码改了模块化的。。我刚试了一下这个是行的，要不try一下

**Comment by pfvlz** [comment]
谢谢

**Comment by pfvlz** [comment]
> > > > > 之前的pr 作者已经合了，默认配置应该就有f参数 发自我的iPhone
> > > > > […](#)
> > > > > 在 2021年4月24日，21:13，pfvlz _**@**_.***> 写道： ﻿ 感谢作者耐心解答，找到了s参数，一个8位数的字符串。但填写完运行脚本提示 "微博app参数验证失败(请重新填写S参数和C参数):客户端身份校验失败" ，不知道是哪里出了问题。 我看了下，其中有一个from字段也是要写进去的，作者在代码里写死了，修改一下就好了 config.json里面 f参数加到后面。运行还是S C参数验证失败。请问在哪里修改？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> > > > 
> > > > 
> > > > 设置了F参数。还是出现这个问题。
> > > 
> > > 
> > > C==android
> > > F是类似`10B4095012`格式的东西
> > 
> > 
> > 是的，已经找到了from值，是你说的这个。运行还是这个问题
> 
> https://github.com/rxrw/signup-weibo
> 完全是作者的代码改了模块化的。。我刚试了一下这个是行的，要不try一下

docker run -v /home/user/docker/signup-weibo:/app -w /app golang:latest go build *.go
我运行这个有问题。不知道怎么弄？请指点下。谢谢
![image](https://user-images.githubusercontent.com/73408957/115984052-9c136300-a5d7-11eb-894c-3dfc28f900a8.png)

**Comment by rxrw** [comment]
> > > > > > 之前的pr 作者已经合了，默认配置应该就有f参数 发自我的iPhone
> > > > > > […](#)
> > > > > > 在 2021年4月24日，21:13，pfvlz _**@**_.***> 写道： ﻿ 感谢作者耐心解答，找到了s参数，一个8位数的字符串。但填写完运行脚本提示 "微博app参数验证失败(请重新填写S参数和C参数):客户端身份校验失败" ，不知道是哪里出了问题。 我看了下，其中有一个from字段也是要写进去的，作者在代码里写死了，修改一下就好了 config.json里面 f参数加到后面。运行还是S C参数验证失败。请问在哪里修改？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> > > > > 
> > > > > 
> > > > > 设置了F参数。还是出现这个问题。
> > > > 
> > > > 
> > > > C==android
> > > > F是类似`10B4095012`格式的东西
> > > 
> > > 
> > > 是的，已经找到了from值，是你说的这个。运行还是这个问题
> > 
> > 
> > https://github.com/rxrw/signup-weibo
> > 完全是作者的代码改了模块化的。。我刚试了一下这个是行的，要不try一下
> 
> docker run -v /home/user/docker/signup-weibo:/app -w /app golang:latest go build *.go
> 我运行这个有问题。不知道怎么弄？请指点下。谢谢
> ![image](https://user-images.githubusercontent.com/73408957/115984052-9c136300-a5d7-11eb-894c-3dfc28f900a8.png)

项目clone到哪里了，比如clone到/home/i/weibo了，那么命令是：docker run -v /home/i/weibo:/app -w /app golang:latest go build *.go

**Comment by wzwcc** [comment]
> > > > > > > 之前的pr 作者已经合了，默认配置应该就有f参数 发自我的iPhone
> > > > > > > […](#)
> > > > > > > 在 2021年4月24日，21:13，pfvlz _**@**_.***> 写道： ﻿ 感谢作者耐心解答，找到了s参数，一个8位数的字符串。但填写完运行脚本提示 "微博app参数验证失败(请重新填写S参数和C参数):客户端身份校验失败" ，不知道是哪里出了问题。 我看了下，其中有一个from字段也是要写进去的，作者在代码里写死了，修改一下就好了 config.json里面 f参数加到后面。运行还是S C参数验证失败。请问在哪里修改？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> > > > > > 
> > > > > > 
> > > > > > 设置了F参数。还是出现这个问题。
> > > > > 
> > > > > 
> > > > > C==android
> > > > > F是类似`10B4095012`格式的东西
> > > > 
> > > > 
> > > > 是的，已经找到了from值，是你说的这个。运行还是这个问题
> > > 
> > > 
> > > https://github.com/rxrw/signup-weibo
> > > 完全是作者的代码改了模块化的。。我刚试了一下这个是行的，要不try一下
> > 
> > 
> > docker run -v /home/user/docker/signup-weibo:/app -w /app golang:latest go build *.go
> > 我运行这个有问题。不知道怎么弄？请指点下。谢谢
> > ![image](https://user-images.githubusercontent.com/73408957/115984052-9c136300-a5d7-11eb-894c-3dfc28f900a8.png)
> 
> 项目clone到哪里了，比如clone到/home/i/weibo了，那么命令是：docker run -v /home/i/weibo:/app -w /app golang:latest go build *.go

![image](https://user-images.githubusercontent.com/76573126/119757373-711e7680-bed7-11eb-957c-6b2ee2543972.png)
![image](https://user-images.githubusercontent.com/76573126/119757419-82678300-bed7-11eb-8d8a-12365c430ea0.png)
+1我也不能编译

**Comment by Fengyinjie** [comment]
参数s 怎么逆向生成呢？有没有人了解这个算法谢谢 @VergilWu @happy888888
