### ISSUE TITLE
签到好像只签了前10个超话列表，然后一直循环签到的那10个，直到最后重启进程

### ISSUE THREAD

**Issue by ylj1314** [happy888888/WeiboTask#8]
<img width="517" alt="image" src="https://user-images.githubusercontent.com/33196759/113369495-0f88d280-9394-11eb-80a0-593cba62ed46.png">

**Comment by rxrw** [comment]
在代码中作者对变量作用域搞混了导致sinceId没有生效，每次刷出来都是那10个超话

**Comment by ylj1314** [comment]
> 在代码中作者对变量作用域搞混了导致sinceId没有生效，每次刷出来都是那10个超话

感谢，现在用其他的了

**Comment by Air433up** [comment]
@ylj1314 请问现在您用的是哪个，可以给个链接嘛？
